// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: video.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_video_2eproto_2epb_2eh
#define GOOGLE_PROTOBUF_INCLUDED_video_2eproto_2epb_2eh

#include <limits>
#include <string>
#include <type_traits>

#include "google/protobuf/port_def.inc"
#if PROTOBUF_VERSION < 4024000
#error "This file was generated by a newer version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please update"
#error "your headers."
#endif  // PROTOBUF_VERSION

#if 4024003 < PROTOBUF_MIN_PROTOC_VERSION
#error "This file was generated by an older version of protoc which is"
#error "incompatible with your Protocol Buffer headers. Please"
#error "regenerate this file with a newer version of protoc."
#endif  // PROTOBUF_MIN_PROTOC_VERSION
#include "google/protobuf/port_undef.inc"
#include "google/protobuf/io/coded_stream.h"
#include "google/protobuf/arena.h"
#include "google/protobuf/arenastring.h"
#include "google/protobuf/generated_message_tctable_decl.h"
#include "google/protobuf/generated_message_util.h"
#include "google/protobuf/metadata_lite.h"
#include "google/protobuf/generated_message_reflection.h"
#include "google/protobuf/message.h"
#include "google/protobuf/repeated_field.h"  // IWYU pragma: export
#include "google/protobuf/extension_set.h"  // IWYU pragma: export
#include "google/protobuf/unknown_field_set.h"
#include "google/protobuf/timestamp.pb.h"
// @@protoc_insertion_point(includes)

// Must be included last.
#include "google/protobuf/port_def.inc"

#define PROTOBUF_INTERNAL_EXPORT_video_2eproto

namespace google {
namespace protobuf {
namespace internal {
class AnyMetadata;
}  // namespace internal
}  // namespace protobuf
}  // namespace google

// Internal implementation detail -- do not use these members.
struct TableStruct_video_2eproto {
  static const ::uint32_t offsets[];
};
extern const ::google::protobuf::internal::DescriptorTable
    descriptor_table_video_2eproto;
namespace prpc {
class Video;
struct VideoDefaultTypeInternal;
extern VideoDefaultTypeInternal _Video_default_instance_;
class VideoFormat;
struct VideoFormatDefaultTypeInternal;
extern VideoFormatDefaultTypeInternal _VideoFormat_default_instance_;
class VideoMetadata;
struct VideoMetadataDefaultTypeInternal;
extern VideoMetadataDefaultTypeInternal _VideoMetadata_default_instance_;
class VideoStream;
struct VideoStreamDefaultTypeInternal;
extern VideoStreamDefaultTypeInternal _VideoStream_default_instance_;
}  // namespace prpc
namespace google {
namespace protobuf {
}  // namespace protobuf
}  // namespace google

namespace prpc {

// ===================================================================


// -------------------------------------------------------------------

class VideoStream final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:prpc.VideoStream) */ {
 public:
  inline VideoStream() : VideoStream(nullptr) {}
  ~VideoStream() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR VideoStream(::google::protobuf::internal::ConstantInitialized);

  VideoStream(const VideoStream& from);
  VideoStream(VideoStream&& from) noexcept
    : VideoStream() {
    *this = ::std::move(from);
  }

  inline VideoStream& operator=(const VideoStream& from) {
    CopyFrom(from);
    return *this;
  }
  inline VideoStream& operator=(VideoStream&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const VideoStream& default_instance() {
    return *internal_default_instance();
  }
  static inline const VideoStream* internal_default_instance() {
    return reinterpret_cast<const VideoStream*>(
               &_VideoStream_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(VideoStream& a, VideoStream& b) {
    a.Swap(&b);
  }
  inline void Swap(VideoStream* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(VideoStream* other) {
    if (other == this) return;
    ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  VideoStream* New(::google::protobuf::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<VideoStream>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const VideoStream& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom( const VideoStream& from) {
    VideoStream::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(VideoStream* other);

  private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "prpc.VideoStream";
  }
  protected:
  explicit VideoStream(::google::protobuf::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::google::protobuf::Message::ClassData*GetClassData() const final;

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kCodecNameFieldNumber = 2,
    kCodecLongNameFieldNumber = 3,
    kProfileFieldNumber = 4,
    kCodecTypeFieldNumber = 5,
    kRFrameRateFieldNumber = 9,
    kIndexFieldNumber = 1,
    kWidthFieldNumber = 6,
    kHeightFieldNumber = 7,
  };
  // string codec_name = 2;
  void clear_codec_name() ;
  const std::string& codec_name() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_codec_name(Arg_&& arg, Args_... args);
  std::string* mutable_codec_name();
  PROTOBUF_NODISCARD std::string* release_codec_name();
  void set_allocated_codec_name(std::string* ptr);

  private:
  const std::string& _internal_codec_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_codec_name(
      const std::string& value);
  std::string* _internal_mutable_codec_name();

  public:
  // string codec_long_name = 3;
  void clear_codec_long_name() ;
  const std::string& codec_long_name() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_codec_long_name(Arg_&& arg, Args_... args);
  std::string* mutable_codec_long_name();
  PROTOBUF_NODISCARD std::string* release_codec_long_name();
  void set_allocated_codec_long_name(std::string* ptr);

  private:
  const std::string& _internal_codec_long_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_codec_long_name(
      const std::string& value);
  std::string* _internal_mutable_codec_long_name();

  public:
  // string profile = 4;
  void clear_profile() ;
  const std::string& profile() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_profile(Arg_&& arg, Args_... args);
  std::string* mutable_profile();
  PROTOBUF_NODISCARD std::string* release_profile();
  void set_allocated_profile(std::string* ptr);

  private:
  const std::string& _internal_profile() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_profile(
      const std::string& value);
  std::string* _internal_mutable_profile();

  public:
  // string codec_type = 5;
  void clear_codec_type() ;
  const std::string& codec_type() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_codec_type(Arg_&& arg, Args_... args);
  std::string* mutable_codec_type();
  PROTOBUF_NODISCARD std::string* release_codec_type();
  void set_allocated_codec_type(std::string* ptr);

  private:
  const std::string& _internal_codec_type() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_codec_type(
      const std::string& value);
  std::string* _internal_mutable_codec_type();

  public:
  // string r_frame_rate = 9;
  void clear_r_frame_rate() ;
  const std::string& r_frame_rate() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_r_frame_rate(Arg_&& arg, Args_... args);
  std::string* mutable_r_frame_rate();
  PROTOBUF_NODISCARD std::string* release_r_frame_rate();
  void set_allocated_r_frame_rate(std::string* ptr);

  private:
  const std::string& _internal_r_frame_rate() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_r_frame_rate(
      const std::string& value);
  std::string* _internal_mutable_r_frame_rate();

  public:
  // int32 index = 1;
  void clear_index() ;
  ::int32_t index() const;
  void set_index(::int32_t value);

  private:
  ::int32_t _internal_index() const;
  void _internal_set_index(::int32_t value);

  public:
  // int32 width = 6;
  void clear_width() ;
  ::int32_t width() const;
  void set_width(::int32_t value);

  private:
  ::int32_t _internal_width() const;
  void _internal_set_width(::int32_t value);

  public:
  // int32 height = 7;
  void clear_height() ;
  ::int32_t height() const;
  void set_height(::int32_t value);

  private:
  ::int32_t _internal_height() const;
  void _internal_set_height(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:prpc.VideoStream)
 private:
  class _Internal;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<4, 8, 0, 87, 2> _table_;
  template <typename T> friend class ::google::protobuf::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::google::protobuf::internal::ArenaStringPtr codec_name_;
    ::google::protobuf::internal::ArenaStringPtr codec_long_name_;
    ::google::protobuf::internal::ArenaStringPtr profile_;
    ::google::protobuf::internal::ArenaStringPtr codec_type_;
    ::google::protobuf::internal::ArenaStringPtr r_frame_rate_;
    ::int32_t index_;
    ::int32_t width_;
    ::int32_t height_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_video_2eproto;
};// -------------------------------------------------------------------

class VideoFormat final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:prpc.VideoFormat) */ {
 public:
  inline VideoFormat() : VideoFormat(nullptr) {}
  ~VideoFormat() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR VideoFormat(::google::protobuf::internal::ConstantInitialized);

  VideoFormat(const VideoFormat& from);
  VideoFormat(VideoFormat&& from) noexcept
    : VideoFormat() {
    *this = ::std::move(from);
  }

  inline VideoFormat& operator=(const VideoFormat& from) {
    CopyFrom(from);
    return *this;
  }
  inline VideoFormat& operator=(VideoFormat&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const VideoFormat& default_instance() {
    return *internal_default_instance();
  }
  static inline const VideoFormat* internal_default_instance() {
    return reinterpret_cast<const VideoFormat*>(
               &_VideoFormat_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(VideoFormat& a, VideoFormat& b) {
    a.Swap(&b);
  }
  inline void Swap(VideoFormat* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(VideoFormat* other) {
    if (other == this) return;
    ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  VideoFormat* New(::google::protobuf::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<VideoFormat>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const VideoFormat& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom( const VideoFormat& from) {
    VideoFormat::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(VideoFormat* other);

  private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "prpc.VideoFormat";
  }
  protected:
  explicit VideoFormat(::google::protobuf::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::google::protobuf::Message::ClassData*GetClassData() const final;

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kFilenameFieldNumber = 1,
    kFormatNameFieldNumber = 3,
    kFormatLongNameFieldNumber = 4,
    kStartTimeFieldNumber = 5,
    kDurationFieldNumber = 6,
    kSizeFieldNumber = 7,
    kBitRateFieldNumber = 8,
    kNbStreamsFieldNumber = 2,
  };
  // string filename = 1;
  void clear_filename() ;
  const std::string& filename() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_filename(Arg_&& arg, Args_... args);
  std::string* mutable_filename();
  PROTOBUF_NODISCARD std::string* release_filename();
  void set_allocated_filename(std::string* ptr);

  private:
  const std::string& _internal_filename() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_filename(
      const std::string& value);
  std::string* _internal_mutable_filename();

  public:
  // string format_name = 3;
  void clear_format_name() ;
  const std::string& format_name() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_format_name(Arg_&& arg, Args_... args);
  std::string* mutable_format_name();
  PROTOBUF_NODISCARD std::string* release_format_name();
  void set_allocated_format_name(std::string* ptr);

  private:
  const std::string& _internal_format_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_format_name(
      const std::string& value);
  std::string* _internal_mutable_format_name();

  public:
  // string format_long_name = 4;
  void clear_format_long_name() ;
  const std::string& format_long_name() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_format_long_name(Arg_&& arg, Args_... args);
  std::string* mutable_format_long_name();
  PROTOBUF_NODISCARD std::string* release_format_long_name();
  void set_allocated_format_long_name(std::string* ptr);

  private:
  const std::string& _internal_format_long_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_format_long_name(
      const std::string& value);
  std::string* _internal_mutable_format_long_name();

  public:
  // string start_time = 5;
  void clear_start_time() ;
  const std::string& start_time() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_start_time(Arg_&& arg, Args_... args);
  std::string* mutable_start_time();
  PROTOBUF_NODISCARD std::string* release_start_time();
  void set_allocated_start_time(std::string* ptr);

  private:
  const std::string& _internal_start_time() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_start_time(
      const std::string& value);
  std::string* _internal_mutable_start_time();

  public:
  // string duration = 6;
  void clear_duration() ;
  const std::string& duration() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_duration(Arg_&& arg, Args_... args);
  std::string* mutable_duration();
  PROTOBUF_NODISCARD std::string* release_duration();
  void set_allocated_duration(std::string* ptr);

  private:
  const std::string& _internal_duration() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_duration(
      const std::string& value);
  std::string* _internal_mutable_duration();

  public:
  // string size = 7;
  void clear_size() ;
  const std::string& size() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_size(Arg_&& arg, Args_... args);
  std::string* mutable_size();
  PROTOBUF_NODISCARD std::string* release_size();
  void set_allocated_size(std::string* ptr);

  private:
  const std::string& _internal_size() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_size(
      const std::string& value);
  std::string* _internal_mutable_size();

  public:
  // string bit_rate = 8;
  void clear_bit_rate() ;
  const std::string& bit_rate() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_bit_rate(Arg_&& arg, Args_... args);
  std::string* mutable_bit_rate();
  PROTOBUF_NODISCARD std::string* release_bit_rate();
  void set_allocated_bit_rate(std::string* ptr);

  private:
  const std::string& _internal_bit_rate() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_bit_rate(
      const std::string& value);
  std::string* _internal_mutable_bit_rate();

  public:
  // int32 nb_streams = 2;
  void clear_nb_streams() ;
  ::int32_t nb_streams() const;
  void set_nb_streams(::int32_t value);

  private:
  ::int32_t _internal_nb_streams() const;
  void _internal_set_nb_streams(::int32_t value);

  public:
  // @@protoc_insertion_point(class_scope:prpc.VideoFormat)
 private:
  class _Internal;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<3, 8, 0, 98, 2> _table_;
  template <typename T> friend class ::google::protobuf::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::google::protobuf::internal::ArenaStringPtr filename_;
    ::google::protobuf::internal::ArenaStringPtr format_name_;
    ::google::protobuf::internal::ArenaStringPtr format_long_name_;
    ::google::protobuf::internal::ArenaStringPtr start_time_;
    ::google::protobuf::internal::ArenaStringPtr duration_;
    ::google::protobuf::internal::ArenaStringPtr size_;
    ::google::protobuf::internal::ArenaStringPtr bit_rate_;
    ::int32_t nb_streams_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_video_2eproto;
};// -------------------------------------------------------------------

class VideoMetadata final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:prpc.VideoMetadata) */ {
 public:
  inline VideoMetadata() : VideoMetadata(nullptr) {}
  ~VideoMetadata() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR VideoMetadata(::google::protobuf::internal::ConstantInitialized);

  VideoMetadata(const VideoMetadata& from);
  VideoMetadata(VideoMetadata&& from) noexcept
    : VideoMetadata() {
    *this = ::std::move(from);
  }

  inline VideoMetadata& operator=(const VideoMetadata& from) {
    CopyFrom(from);
    return *this;
  }
  inline VideoMetadata& operator=(VideoMetadata&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const VideoMetadata& default_instance() {
    return *internal_default_instance();
  }
  static inline const VideoMetadata* internal_default_instance() {
    return reinterpret_cast<const VideoMetadata*>(
               &_VideoMetadata_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    2;

  friend void swap(VideoMetadata& a, VideoMetadata& b) {
    a.Swap(&b);
  }
  inline void Swap(VideoMetadata* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(VideoMetadata* other) {
    if (other == this) return;
    ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  VideoMetadata* New(::google::protobuf::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<VideoMetadata>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const VideoMetadata& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom( const VideoMetadata& from) {
    VideoMetadata::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(VideoMetadata* other);

  private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "prpc.VideoMetadata";
  }
  protected:
  explicit VideoMetadata(::google::protobuf::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::google::protobuf::Message::ClassData*GetClassData() const final;

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kStreamsFieldNumber = 1,
    kFormatFieldNumber = 2,
  };
  // repeated .prpc.VideoStream streams = 1;
  int streams_size() const;
  private:
  int _internal_streams_size() const;

  public:
  void clear_streams() ;
  ::prpc::VideoStream* mutable_streams(int index);
  ::google::protobuf::RepeatedPtrField< ::prpc::VideoStream >*
      mutable_streams();
  private:
  const ::google::protobuf::RepeatedPtrField<::prpc::VideoStream>& _internal_streams() const;
  ::google::protobuf::RepeatedPtrField<::prpc::VideoStream>* _internal_mutable_streams();
  public:
  const ::prpc::VideoStream& streams(int index) const;
  ::prpc::VideoStream* add_streams();
  const ::google::protobuf::RepeatedPtrField< ::prpc::VideoStream >&
      streams() const;
  // .prpc.VideoFormat format = 2;
  bool has_format() const;
  void clear_format() ;
  const ::prpc::VideoFormat& format() const;
  PROTOBUF_NODISCARD ::prpc::VideoFormat* release_format();
  ::prpc::VideoFormat* mutable_format();
  void set_allocated_format(::prpc::VideoFormat* value);
  void unsafe_arena_set_allocated_format(::prpc::VideoFormat* value);
  ::prpc::VideoFormat* unsafe_arena_release_format();

  private:
  const ::prpc::VideoFormat& _internal_format() const;
  ::prpc::VideoFormat* _internal_mutable_format();

  public:
  // @@protoc_insertion_point(class_scope:prpc.VideoMetadata)
 private:
  class _Internal;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<1, 2, 2, 0, 2> _table_;
  template <typename T> friend class ::google::protobuf::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedPtrField< ::prpc::VideoStream > streams_;
    ::prpc::VideoFormat* format_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_video_2eproto;
};// -------------------------------------------------------------------

class Video final :
    public ::google::protobuf::Message /* @@protoc_insertion_point(class_definition:prpc.Video) */ {
 public:
  inline Video() : Video(nullptr) {}
  ~Video() override;
  template<typename = void>
  explicit PROTOBUF_CONSTEXPR Video(::google::protobuf::internal::ConstantInitialized);

  Video(const Video& from);
  Video(Video&& from) noexcept
    : Video() {
    *this = ::std::move(from);
  }

  inline Video& operator=(const Video& from) {
    CopyFrom(from);
    return *this;
  }
  inline Video& operator=(Video&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  inline const ::google::protobuf::UnknownFieldSet& unknown_fields() const {
    return _internal_metadata_.unknown_fields<::google::protobuf::UnknownFieldSet>(::google::protobuf::UnknownFieldSet::default_instance);
  }
  inline ::google::protobuf::UnknownFieldSet* mutable_unknown_fields() {
    return _internal_metadata_.mutable_unknown_fields<::google::protobuf::UnknownFieldSet>();
  }

  static const ::google::protobuf::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::google::protobuf::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::google::protobuf::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Video& default_instance() {
    return *internal_default_instance();
  }
  static inline const Video* internal_default_instance() {
    return reinterpret_cast<const Video*>(
               &_Video_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    3;

  friend void swap(Video& a, Video& b) {
    a.Swap(&b);
  }
  inline void Swap(Video* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::google::protobuf::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Video* other) {
    if (other == this) return;
    ABSL_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Video* New(::google::protobuf::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Video>(arena);
  }
  using ::google::protobuf::Message::CopyFrom;
  void CopyFrom(const Video& from);
  using ::google::protobuf::Message::MergeFrom;
  void MergeFrom( const Video& from) {
    Video::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::google::protobuf::Message& to_msg, const ::google::protobuf::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  ::size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::google::protobuf::internal::ParseContext* ctx) final;
  ::uint8_t* _InternalSerialize(
      ::uint8_t* target, ::google::protobuf::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::google::protobuf::Arena* arena);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Video* other);

  private:
  friend class ::google::protobuf::internal::AnyMetadata;
  static ::absl::string_view FullMessageName() {
    return "prpc.Video";
  }
  protected:
  explicit Video(::google::protobuf::Arena* arena);
  public:

  static const ClassData _class_data_;
  const ::google::protobuf::Message::ClassData*GetClassData() const final;

  ::google::protobuf::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kSubtitlePathsFieldNumber = 4,
    kNameFieldNumber = 2,
    kMetaFieldNumber = 3,
    kIdFieldNumber = 1,
  };
  // repeated string subtitle_paths = 4;
  int subtitle_paths_size() const;
  private:
  int _internal_subtitle_paths_size() const;

  public:
  void clear_subtitle_paths() ;
  const std::string& subtitle_paths(int index) const;
  std::string* mutable_subtitle_paths(int index);
  void set_subtitle_paths(int index, const std::string& value);
  void set_subtitle_paths(int index, std::string&& value);
  void set_subtitle_paths(int index, const char* value);
  void set_subtitle_paths(int index, const char* value, std::size_t size);
  void set_subtitle_paths(int index, absl::string_view value);
  std::string* add_subtitle_paths();
  void add_subtitle_paths(const std::string& value);
  void add_subtitle_paths(std::string&& value);
  void add_subtitle_paths(const char* value);
  void add_subtitle_paths(const char* value, std::size_t size);
  void add_subtitle_paths(absl::string_view value);
  const ::google::protobuf::RepeatedPtrField<std::string>& subtitle_paths() const;
  ::google::protobuf::RepeatedPtrField<std::string>* mutable_subtitle_paths();

  private:
  const ::google::protobuf::RepeatedPtrField<std::string>& _internal_subtitle_paths() const;
  ::google::protobuf::RepeatedPtrField<std::string>* _internal_mutable_subtitle_paths();

  public:
  // string name = 2;
  void clear_name() ;
  const std::string& name() const;
  template <typename Arg_ = const std::string&, typename... Args_>
  void set_name(Arg_&& arg, Args_... args);
  std::string* mutable_name();
  PROTOBUF_NODISCARD std::string* release_name();
  void set_allocated_name(std::string* ptr);

  private:
  const std::string& _internal_name() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_name(
      const std::string& value);
  std::string* _internal_mutable_name();

  public:
  // .prpc.VideoMetadata meta = 3;
  bool has_meta() const;
  void clear_meta() ;
  const ::prpc::VideoMetadata& meta() const;
  PROTOBUF_NODISCARD ::prpc::VideoMetadata* release_meta();
  ::prpc::VideoMetadata* mutable_meta();
  void set_allocated_meta(::prpc::VideoMetadata* value);
  void unsafe_arena_set_allocated_meta(::prpc::VideoMetadata* value);
  ::prpc::VideoMetadata* unsafe_arena_release_meta();

  private:
  const ::prpc::VideoMetadata& _internal_meta() const;
  ::prpc::VideoMetadata* _internal_mutable_meta();

  public:
  // int64 id = 1;
  void clear_id() ;
  ::int64_t id() const;
  void set_id(::int64_t value);

  private:
  ::int64_t _internal_id() const;
  void _internal_set_id(::int64_t value);

  public:
  // @@protoc_insertion_point(class_scope:prpc.Video)
 private:
  class _Internal;

  friend class ::google::protobuf::internal::TcParser;
  static const ::google::protobuf::internal::TcParseTable<2, 4, 1, 37, 2> _table_;
  template <typename T> friend class ::google::protobuf::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::google::protobuf::internal::HasBits<1> _has_bits_;
    mutable ::google::protobuf::internal::CachedSize _cached_size_;
    ::google::protobuf::RepeatedPtrField<std::string> subtitle_paths_;
    ::google::protobuf::internal::ArenaStringPtr name_;
    ::prpc::VideoMetadata* meta_;
    ::int64_t id_;
    PROTOBUF_TSAN_DECLARE_MEMBER
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_video_2eproto;
};

// ===================================================================




// ===================================================================


#ifdef __GNUC__
#pragma GCC diagnostic push
#pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// -------------------------------------------------------------------

// VideoStream

// int32 index = 1;
inline void VideoStream::clear_index() {
  _impl_.index_ = 0;
}
inline ::int32_t VideoStream::index() const {
  // @@protoc_insertion_point(field_get:prpc.VideoStream.index)
  return _internal_index();
}
inline void VideoStream::set_index(::int32_t value) {
  _internal_set_index(value);
  // @@protoc_insertion_point(field_set:prpc.VideoStream.index)
}
inline ::int32_t VideoStream::_internal_index() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.index_;
}
inline void VideoStream::_internal_set_index(::int32_t value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.index_ = value;
}

// string codec_name = 2;
inline void VideoStream::clear_codec_name() {
  _impl_.codec_name_.ClearToEmpty();
}
inline const std::string& VideoStream::codec_name() const {
  // @@protoc_insertion_point(field_get:prpc.VideoStream.codec_name)
  return _internal_codec_name();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void VideoStream::set_codec_name(Arg_&& arg,
                                                     Args_... args) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.codec_name_.Set(static_cast<Arg_&&>(arg), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:prpc.VideoStream.codec_name)
}
inline std::string* VideoStream::mutable_codec_name() {
  std::string* _s = _internal_mutable_codec_name();
  // @@protoc_insertion_point(field_mutable:prpc.VideoStream.codec_name)
  return _s;
}
inline const std::string& VideoStream::_internal_codec_name() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.codec_name_.Get();
}
inline void VideoStream::_internal_set_codec_name(const std::string& value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.codec_name_.Set(value, GetArenaForAllocation());
}
inline std::string* VideoStream::_internal_mutable_codec_name() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  return _impl_.codec_name_.Mutable( GetArenaForAllocation());
}
inline std::string* VideoStream::release_codec_name() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:prpc.VideoStream.codec_name)
  return _impl_.codec_name_.Release();
}
inline void VideoStream::set_allocated_codec_name(std::string* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.codec_name_.SetAllocated(value, GetArenaForAllocation());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.codec_name_.IsDefault()) {
          _impl_.codec_name_.Set("", GetArenaForAllocation());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:prpc.VideoStream.codec_name)
}

// string codec_long_name = 3;
inline void VideoStream::clear_codec_long_name() {
  _impl_.codec_long_name_.ClearToEmpty();
}
inline const std::string& VideoStream::codec_long_name() const {
  // @@protoc_insertion_point(field_get:prpc.VideoStream.codec_long_name)
  return _internal_codec_long_name();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void VideoStream::set_codec_long_name(Arg_&& arg,
                                                     Args_... args) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.codec_long_name_.Set(static_cast<Arg_&&>(arg), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:prpc.VideoStream.codec_long_name)
}
inline std::string* VideoStream::mutable_codec_long_name() {
  std::string* _s = _internal_mutable_codec_long_name();
  // @@protoc_insertion_point(field_mutable:prpc.VideoStream.codec_long_name)
  return _s;
}
inline const std::string& VideoStream::_internal_codec_long_name() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.codec_long_name_.Get();
}
inline void VideoStream::_internal_set_codec_long_name(const std::string& value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.codec_long_name_.Set(value, GetArenaForAllocation());
}
inline std::string* VideoStream::_internal_mutable_codec_long_name() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  return _impl_.codec_long_name_.Mutable( GetArenaForAllocation());
}
inline std::string* VideoStream::release_codec_long_name() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:prpc.VideoStream.codec_long_name)
  return _impl_.codec_long_name_.Release();
}
inline void VideoStream::set_allocated_codec_long_name(std::string* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.codec_long_name_.SetAllocated(value, GetArenaForAllocation());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.codec_long_name_.IsDefault()) {
          _impl_.codec_long_name_.Set("", GetArenaForAllocation());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:prpc.VideoStream.codec_long_name)
}

// string profile = 4;
inline void VideoStream::clear_profile() {
  _impl_.profile_.ClearToEmpty();
}
inline const std::string& VideoStream::profile() const {
  // @@protoc_insertion_point(field_get:prpc.VideoStream.profile)
  return _internal_profile();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void VideoStream::set_profile(Arg_&& arg,
                                                     Args_... args) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.profile_.Set(static_cast<Arg_&&>(arg), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:prpc.VideoStream.profile)
}
inline std::string* VideoStream::mutable_profile() {
  std::string* _s = _internal_mutable_profile();
  // @@protoc_insertion_point(field_mutable:prpc.VideoStream.profile)
  return _s;
}
inline const std::string& VideoStream::_internal_profile() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.profile_.Get();
}
inline void VideoStream::_internal_set_profile(const std::string& value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.profile_.Set(value, GetArenaForAllocation());
}
inline std::string* VideoStream::_internal_mutable_profile() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  return _impl_.profile_.Mutable( GetArenaForAllocation());
}
inline std::string* VideoStream::release_profile() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:prpc.VideoStream.profile)
  return _impl_.profile_.Release();
}
inline void VideoStream::set_allocated_profile(std::string* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.profile_.SetAllocated(value, GetArenaForAllocation());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.profile_.IsDefault()) {
          _impl_.profile_.Set("", GetArenaForAllocation());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:prpc.VideoStream.profile)
}

// string codec_type = 5;
inline void VideoStream::clear_codec_type() {
  _impl_.codec_type_.ClearToEmpty();
}
inline const std::string& VideoStream::codec_type() const {
  // @@protoc_insertion_point(field_get:prpc.VideoStream.codec_type)
  return _internal_codec_type();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void VideoStream::set_codec_type(Arg_&& arg,
                                                     Args_... args) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.codec_type_.Set(static_cast<Arg_&&>(arg), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:prpc.VideoStream.codec_type)
}
inline std::string* VideoStream::mutable_codec_type() {
  std::string* _s = _internal_mutable_codec_type();
  // @@protoc_insertion_point(field_mutable:prpc.VideoStream.codec_type)
  return _s;
}
inline const std::string& VideoStream::_internal_codec_type() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.codec_type_.Get();
}
inline void VideoStream::_internal_set_codec_type(const std::string& value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.codec_type_.Set(value, GetArenaForAllocation());
}
inline std::string* VideoStream::_internal_mutable_codec_type() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  return _impl_.codec_type_.Mutable( GetArenaForAllocation());
}
inline std::string* VideoStream::release_codec_type() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:prpc.VideoStream.codec_type)
  return _impl_.codec_type_.Release();
}
inline void VideoStream::set_allocated_codec_type(std::string* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.codec_type_.SetAllocated(value, GetArenaForAllocation());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.codec_type_.IsDefault()) {
          _impl_.codec_type_.Set("", GetArenaForAllocation());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:prpc.VideoStream.codec_type)
}

// int32 width = 6;
inline void VideoStream::clear_width() {
  _impl_.width_ = 0;
}
inline ::int32_t VideoStream::width() const {
  // @@protoc_insertion_point(field_get:prpc.VideoStream.width)
  return _internal_width();
}
inline void VideoStream::set_width(::int32_t value) {
  _internal_set_width(value);
  // @@protoc_insertion_point(field_set:prpc.VideoStream.width)
}
inline ::int32_t VideoStream::_internal_width() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.width_;
}
inline void VideoStream::_internal_set_width(::int32_t value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.width_ = value;
}

// int32 height = 7;
inline void VideoStream::clear_height() {
  _impl_.height_ = 0;
}
inline ::int32_t VideoStream::height() const {
  // @@protoc_insertion_point(field_get:prpc.VideoStream.height)
  return _internal_height();
}
inline void VideoStream::set_height(::int32_t value) {
  _internal_set_height(value);
  // @@protoc_insertion_point(field_set:prpc.VideoStream.height)
}
inline ::int32_t VideoStream::_internal_height() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.height_;
}
inline void VideoStream::_internal_set_height(::int32_t value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.height_ = value;
}

// string r_frame_rate = 9;
inline void VideoStream::clear_r_frame_rate() {
  _impl_.r_frame_rate_.ClearToEmpty();
}
inline const std::string& VideoStream::r_frame_rate() const {
  // @@protoc_insertion_point(field_get:prpc.VideoStream.r_frame_rate)
  return _internal_r_frame_rate();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void VideoStream::set_r_frame_rate(Arg_&& arg,
                                                     Args_... args) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.r_frame_rate_.Set(static_cast<Arg_&&>(arg), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:prpc.VideoStream.r_frame_rate)
}
inline std::string* VideoStream::mutable_r_frame_rate() {
  std::string* _s = _internal_mutable_r_frame_rate();
  // @@protoc_insertion_point(field_mutable:prpc.VideoStream.r_frame_rate)
  return _s;
}
inline const std::string& VideoStream::_internal_r_frame_rate() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.r_frame_rate_.Get();
}
inline void VideoStream::_internal_set_r_frame_rate(const std::string& value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.r_frame_rate_.Set(value, GetArenaForAllocation());
}
inline std::string* VideoStream::_internal_mutable_r_frame_rate() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  return _impl_.r_frame_rate_.Mutable( GetArenaForAllocation());
}
inline std::string* VideoStream::release_r_frame_rate() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:prpc.VideoStream.r_frame_rate)
  return _impl_.r_frame_rate_.Release();
}
inline void VideoStream::set_allocated_r_frame_rate(std::string* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.r_frame_rate_.SetAllocated(value, GetArenaForAllocation());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.r_frame_rate_.IsDefault()) {
          _impl_.r_frame_rate_.Set("", GetArenaForAllocation());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:prpc.VideoStream.r_frame_rate)
}

// -------------------------------------------------------------------

// VideoFormat

// string filename = 1;
inline void VideoFormat::clear_filename() {
  _impl_.filename_.ClearToEmpty();
}
inline const std::string& VideoFormat::filename() const {
  // @@protoc_insertion_point(field_get:prpc.VideoFormat.filename)
  return _internal_filename();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void VideoFormat::set_filename(Arg_&& arg,
                                                     Args_... args) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.filename_.Set(static_cast<Arg_&&>(arg), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:prpc.VideoFormat.filename)
}
inline std::string* VideoFormat::mutable_filename() {
  std::string* _s = _internal_mutable_filename();
  // @@protoc_insertion_point(field_mutable:prpc.VideoFormat.filename)
  return _s;
}
inline const std::string& VideoFormat::_internal_filename() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.filename_.Get();
}
inline void VideoFormat::_internal_set_filename(const std::string& value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.filename_.Set(value, GetArenaForAllocation());
}
inline std::string* VideoFormat::_internal_mutable_filename() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  return _impl_.filename_.Mutable( GetArenaForAllocation());
}
inline std::string* VideoFormat::release_filename() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:prpc.VideoFormat.filename)
  return _impl_.filename_.Release();
}
inline void VideoFormat::set_allocated_filename(std::string* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.filename_.SetAllocated(value, GetArenaForAllocation());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.filename_.IsDefault()) {
          _impl_.filename_.Set("", GetArenaForAllocation());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:prpc.VideoFormat.filename)
}

// int32 nb_streams = 2;
inline void VideoFormat::clear_nb_streams() {
  _impl_.nb_streams_ = 0;
}
inline ::int32_t VideoFormat::nb_streams() const {
  // @@protoc_insertion_point(field_get:prpc.VideoFormat.nb_streams)
  return _internal_nb_streams();
}
inline void VideoFormat::set_nb_streams(::int32_t value) {
  _internal_set_nb_streams(value);
  // @@protoc_insertion_point(field_set:prpc.VideoFormat.nb_streams)
}
inline ::int32_t VideoFormat::_internal_nb_streams() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.nb_streams_;
}
inline void VideoFormat::_internal_set_nb_streams(::int32_t value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.nb_streams_ = value;
}

// string format_name = 3;
inline void VideoFormat::clear_format_name() {
  _impl_.format_name_.ClearToEmpty();
}
inline const std::string& VideoFormat::format_name() const {
  // @@protoc_insertion_point(field_get:prpc.VideoFormat.format_name)
  return _internal_format_name();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void VideoFormat::set_format_name(Arg_&& arg,
                                                     Args_... args) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.format_name_.Set(static_cast<Arg_&&>(arg), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:prpc.VideoFormat.format_name)
}
inline std::string* VideoFormat::mutable_format_name() {
  std::string* _s = _internal_mutable_format_name();
  // @@protoc_insertion_point(field_mutable:prpc.VideoFormat.format_name)
  return _s;
}
inline const std::string& VideoFormat::_internal_format_name() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.format_name_.Get();
}
inline void VideoFormat::_internal_set_format_name(const std::string& value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.format_name_.Set(value, GetArenaForAllocation());
}
inline std::string* VideoFormat::_internal_mutable_format_name() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  return _impl_.format_name_.Mutable( GetArenaForAllocation());
}
inline std::string* VideoFormat::release_format_name() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:prpc.VideoFormat.format_name)
  return _impl_.format_name_.Release();
}
inline void VideoFormat::set_allocated_format_name(std::string* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.format_name_.SetAllocated(value, GetArenaForAllocation());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.format_name_.IsDefault()) {
          _impl_.format_name_.Set("", GetArenaForAllocation());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:prpc.VideoFormat.format_name)
}

// string format_long_name = 4;
inline void VideoFormat::clear_format_long_name() {
  _impl_.format_long_name_.ClearToEmpty();
}
inline const std::string& VideoFormat::format_long_name() const {
  // @@protoc_insertion_point(field_get:prpc.VideoFormat.format_long_name)
  return _internal_format_long_name();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void VideoFormat::set_format_long_name(Arg_&& arg,
                                                     Args_... args) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.format_long_name_.Set(static_cast<Arg_&&>(arg), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:prpc.VideoFormat.format_long_name)
}
inline std::string* VideoFormat::mutable_format_long_name() {
  std::string* _s = _internal_mutable_format_long_name();
  // @@protoc_insertion_point(field_mutable:prpc.VideoFormat.format_long_name)
  return _s;
}
inline const std::string& VideoFormat::_internal_format_long_name() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.format_long_name_.Get();
}
inline void VideoFormat::_internal_set_format_long_name(const std::string& value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.format_long_name_.Set(value, GetArenaForAllocation());
}
inline std::string* VideoFormat::_internal_mutable_format_long_name() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  return _impl_.format_long_name_.Mutable( GetArenaForAllocation());
}
inline std::string* VideoFormat::release_format_long_name() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:prpc.VideoFormat.format_long_name)
  return _impl_.format_long_name_.Release();
}
inline void VideoFormat::set_allocated_format_long_name(std::string* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.format_long_name_.SetAllocated(value, GetArenaForAllocation());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.format_long_name_.IsDefault()) {
          _impl_.format_long_name_.Set("", GetArenaForAllocation());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:prpc.VideoFormat.format_long_name)
}

// string start_time = 5;
inline void VideoFormat::clear_start_time() {
  _impl_.start_time_.ClearToEmpty();
}
inline const std::string& VideoFormat::start_time() const {
  // @@protoc_insertion_point(field_get:prpc.VideoFormat.start_time)
  return _internal_start_time();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void VideoFormat::set_start_time(Arg_&& arg,
                                                     Args_... args) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.start_time_.Set(static_cast<Arg_&&>(arg), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:prpc.VideoFormat.start_time)
}
inline std::string* VideoFormat::mutable_start_time() {
  std::string* _s = _internal_mutable_start_time();
  // @@protoc_insertion_point(field_mutable:prpc.VideoFormat.start_time)
  return _s;
}
inline const std::string& VideoFormat::_internal_start_time() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.start_time_.Get();
}
inline void VideoFormat::_internal_set_start_time(const std::string& value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.start_time_.Set(value, GetArenaForAllocation());
}
inline std::string* VideoFormat::_internal_mutable_start_time() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  return _impl_.start_time_.Mutable( GetArenaForAllocation());
}
inline std::string* VideoFormat::release_start_time() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:prpc.VideoFormat.start_time)
  return _impl_.start_time_.Release();
}
inline void VideoFormat::set_allocated_start_time(std::string* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.start_time_.SetAllocated(value, GetArenaForAllocation());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.start_time_.IsDefault()) {
          _impl_.start_time_.Set("", GetArenaForAllocation());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:prpc.VideoFormat.start_time)
}

// string duration = 6;
inline void VideoFormat::clear_duration() {
  _impl_.duration_.ClearToEmpty();
}
inline const std::string& VideoFormat::duration() const {
  // @@protoc_insertion_point(field_get:prpc.VideoFormat.duration)
  return _internal_duration();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void VideoFormat::set_duration(Arg_&& arg,
                                                     Args_... args) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.duration_.Set(static_cast<Arg_&&>(arg), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:prpc.VideoFormat.duration)
}
inline std::string* VideoFormat::mutable_duration() {
  std::string* _s = _internal_mutable_duration();
  // @@protoc_insertion_point(field_mutable:prpc.VideoFormat.duration)
  return _s;
}
inline const std::string& VideoFormat::_internal_duration() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.duration_.Get();
}
inline void VideoFormat::_internal_set_duration(const std::string& value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.duration_.Set(value, GetArenaForAllocation());
}
inline std::string* VideoFormat::_internal_mutable_duration() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  return _impl_.duration_.Mutable( GetArenaForAllocation());
}
inline std::string* VideoFormat::release_duration() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:prpc.VideoFormat.duration)
  return _impl_.duration_.Release();
}
inline void VideoFormat::set_allocated_duration(std::string* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.duration_.SetAllocated(value, GetArenaForAllocation());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.duration_.IsDefault()) {
          _impl_.duration_.Set("", GetArenaForAllocation());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:prpc.VideoFormat.duration)
}

// string size = 7;
inline void VideoFormat::clear_size() {
  _impl_.size_.ClearToEmpty();
}
inline const std::string& VideoFormat::size() const {
  // @@protoc_insertion_point(field_get:prpc.VideoFormat.size)
  return _internal_size();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void VideoFormat::set_size(Arg_&& arg,
                                                     Args_... args) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.size_.Set(static_cast<Arg_&&>(arg), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:prpc.VideoFormat.size)
}
inline std::string* VideoFormat::mutable_size() {
  std::string* _s = _internal_mutable_size();
  // @@protoc_insertion_point(field_mutable:prpc.VideoFormat.size)
  return _s;
}
inline const std::string& VideoFormat::_internal_size() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.size_.Get();
}
inline void VideoFormat::_internal_set_size(const std::string& value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.size_.Set(value, GetArenaForAllocation());
}
inline std::string* VideoFormat::_internal_mutable_size() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  return _impl_.size_.Mutable( GetArenaForAllocation());
}
inline std::string* VideoFormat::release_size() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:prpc.VideoFormat.size)
  return _impl_.size_.Release();
}
inline void VideoFormat::set_allocated_size(std::string* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.size_.SetAllocated(value, GetArenaForAllocation());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.size_.IsDefault()) {
          _impl_.size_.Set("", GetArenaForAllocation());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:prpc.VideoFormat.size)
}

// string bit_rate = 8;
inline void VideoFormat::clear_bit_rate() {
  _impl_.bit_rate_.ClearToEmpty();
}
inline const std::string& VideoFormat::bit_rate() const {
  // @@protoc_insertion_point(field_get:prpc.VideoFormat.bit_rate)
  return _internal_bit_rate();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void VideoFormat::set_bit_rate(Arg_&& arg,
                                                     Args_... args) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.bit_rate_.Set(static_cast<Arg_&&>(arg), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:prpc.VideoFormat.bit_rate)
}
inline std::string* VideoFormat::mutable_bit_rate() {
  std::string* _s = _internal_mutable_bit_rate();
  // @@protoc_insertion_point(field_mutable:prpc.VideoFormat.bit_rate)
  return _s;
}
inline const std::string& VideoFormat::_internal_bit_rate() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.bit_rate_.Get();
}
inline void VideoFormat::_internal_set_bit_rate(const std::string& value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.bit_rate_.Set(value, GetArenaForAllocation());
}
inline std::string* VideoFormat::_internal_mutable_bit_rate() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  return _impl_.bit_rate_.Mutable( GetArenaForAllocation());
}
inline std::string* VideoFormat::release_bit_rate() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:prpc.VideoFormat.bit_rate)
  return _impl_.bit_rate_.Release();
}
inline void VideoFormat::set_allocated_bit_rate(std::string* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.bit_rate_.SetAllocated(value, GetArenaForAllocation());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.bit_rate_.IsDefault()) {
          _impl_.bit_rate_.Set("", GetArenaForAllocation());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:prpc.VideoFormat.bit_rate)
}

// -------------------------------------------------------------------

// VideoMetadata

// repeated .prpc.VideoStream streams = 1;
inline int VideoMetadata::_internal_streams_size() const {
  return _internal_streams().size();
}
inline int VideoMetadata::streams_size() const {
  return _internal_streams_size();
}
inline void VideoMetadata::clear_streams() {
  _internal_mutable_streams()->Clear();
}
inline ::prpc::VideoStream* VideoMetadata::mutable_streams(int index) {
  // @@protoc_insertion_point(field_mutable:prpc.VideoMetadata.streams)
  return _internal_mutable_streams()->Mutable(index);
}
inline ::google::protobuf::RepeatedPtrField< ::prpc::VideoStream >*
VideoMetadata::mutable_streams() {
  // @@protoc_insertion_point(field_mutable_list:prpc.VideoMetadata.streams)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  return _internal_mutable_streams();
}
inline const ::prpc::VideoStream& VideoMetadata::streams(int index) const {
  // @@protoc_insertion_point(field_get:prpc.VideoMetadata.streams)
    return _internal_streams().Get(index);
}
inline ::prpc::VideoStream* VideoMetadata::add_streams() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ::prpc::VideoStream* _add = _internal_mutable_streams()->Add();
  // @@protoc_insertion_point(field_add:prpc.VideoMetadata.streams)
  return _add;
}
inline const ::google::protobuf::RepeatedPtrField< ::prpc::VideoStream >&
VideoMetadata::streams() const {
  // @@protoc_insertion_point(field_list:prpc.VideoMetadata.streams)
  return _internal_streams();
}
inline const ::google::protobuf::RepeatedPtrField<::prpc::VideoStream>&
VideoMetadata::_internal_streams() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.streams_;
}
inline ::google::protobuf::RepeatedPtrField<::prpc::VideoStream>*
VideoMetadata::_internal_mutable_streams() {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return &_impl_.streams_;
}

// .prpc.VideoFormat format = 2;
inline bool VideoMetadata::has_format() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.format_ != nullptr);
  return value;
}
inline void VideoMetadata::clear_format() {
  if (_impl_.format_ != nullptr) _impl_.format_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const ::prpc::VideoFormat& VideoMetadata::_internal_format() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  const ::prpc::VideoFormat* p = _impl_.format_;
  return p != nullptr ? *p : reinterpret_cast<const ::prpc::VideoFormat&>(::prpc::_VideoFormat_default_instance_);
}
inline const ::prpc::VideoFormat& VideoMetadata::format() const {
  // @@protoc_insertion_point(field_get:prpc.VideoMetadata.format)
  return _internal_format();
}
inline void VideoMetadata::unsafe_arena_set_allocated_format(::prpc::VideoFormat* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.format_);
  }
  _impl_.format_ = reinterpret_cast<::prpc::VideoFormat*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:prpc.VideoMetadata.format)
}
inline ::prpc::VideoFormat* VideoMetadata::release_format() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::prpc::VideoFormat* released = _impl_.format_;
  _impl_.format_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
  released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  if (GetArenaForAllocation() == nullptr) {
    delete old;
  }
#else   // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return released;
}
inline ::prpc::VideoFormat* VideoMetadata::unsafe_arena_release_format() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:prpc.VideoMetadata.format)

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::prpc::VideoFormat* temp = _impl_.format_;
  _impl_.format_ = nullptr;
  return temp;
}
inline ::prpc::VideoFormat* VideoMetadata::_internal_mutable_format() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000001u;
  if (_impl_.format_ == nullptr) {
    auto* p = CreateMaybeMessage<::prpc::VideoFormat>(GetArenaForAllocation());
    _impl_.format_ = reinterpret_cast<::prpc::VideoFormat*>(p);
  }
  return _impl_.format_;
}
inline ::prpc::VideoFormat* VideoMetadata::mutable_format() {
  ::prpc::VideoFormat* _msg = _internal_mutable_format();
  // @@protoc_insertion_point(field_mutable:prpc.VideoMetadata.format)
  return _msg;
}
inline void VideoMetadata::set_allocated_format(::prpc::VideoFormat* value) {
  ::google::protobuf::Arena* message_arena = GetArenaForAllocation();
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::prpc::VideoFormat*>(_impl_.format_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena =
        ::google::protobuf::Arena::InternalGetOwningArena(reinterpret_cast<::prpc::VideoFormat*>(value));
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }

  _impl_.format_ = reinterpret_cast<::prpc::VideoFormat*>(value);
  // @@protoc_insertion_point(field_set_allocated:prpc.VideoMetadata.format)
}

// -------------------------------------------------------------------

// Video

// int64 id = 1;
inline void Video::clear_id() {
  _impl_.id_ = ::int64_t{0};
}
inline ::int64_t Video::id() const {
  // @@protoc_insertion_point(field_get:prpc.Video.id)
  return _internal_id();
}
inline void Video::set_id(::int64_t value) {
  _internal_set_id(value);
  // @@protoc_insertion_point(field_set:prpc.Video.id)
}
inline ::int64_t Video::_internal_id() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.id_;
}
inline void Video::_internal_set_id(::int64_t value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.id_ = value;
}

// string name = 2;
inline void Video::clear_name() {
  _impl_.name_.ClearToEmpty();
}
inline const std::string& Video::name() const {
  // @@protoc_insertion_point(field_get:prpc.Video.name)
  return _internal_name();
}
template <typename Arg_, typename... Args_>
inline PROTOBUF_ALWAYS_INLINE void Video::set_name(Arg_&& arg,
                                                     Args_... args) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.name_.Set(static_cast<Arg_&&>(arg), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:prpc.Video.name)
}
inline std::string* Video::mutable_name() {
  std::string* _s = _internal_mutable_name();
  // @@protoc_insertion_point(field_mutable:prpc.Video.name)
  return _s;
}
inline const std::string& Video::_internal_name() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.name_.Get();
}
inline void Video::_internal_set_name(const std::string& value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  _impl_.name_.Set(value, GetArenaForAllocation());
}
inline std::string* Video::_internal_mutable_name() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  ;
  return _impl_.name_.Mutable( GetArenaForAllocation());
}
inline std::string* Video::release_name() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:prpc.Video.name)
  return _impl_.name_.Release();
}
inline void Video::set_allocated_name(std::string* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_.name_.SetAllocated(value, GetArenaForAllocation());
  #ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
        if (_impl_.name_.IsDefault()) {
          _impl_.name_.Set("", GetArenaForAllocation());
        }
  #endif  // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:prpc.Video.name)
}

// .prpc.VideoMetadata meta = 3;
inline bool Video::has_meta() const {
  bool value = (_impl_._has_bits_[0] & 0x00000001u) != 0;
  PROTOBUF_ASSUME(!value || _impl_.meta_ != nullptr);
  return value;
}
inline void Video::clear_meta() {
  if (_impl_.meta_ != nullptr) _impl_.meta_->Clear();
  _impl_._has_bits_[0] &= ~0x00000001u;
}
inline const ::prpc::VideoMetadata& Video::_internal_meta() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  const ::prpc::VideoMetadata* p = _impl_.meta_;
  return p != nullptr ? *p : reinterpret_cast<const ::prpc::VideoMetadata&>(::prpc::_VideoMetadata_default_instance_);
}
inline const ::prpc::VideoMetadata& Video::meta() const {
  // @@protoc_insertion_point(field_get:prpc.Video.meta)
  return _internal_meta();
}
inline void Video::unsafe_arena_set_allocated_meta(::prpc::VideoMetadata* value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (GetArenaForAllocation() == nullptr) {
    delete reinterpret_cast<::google::protobuf::MessageLite*>(_impl_.meta_);
  }
  _impl_.meta_ = reinterpret_cast<::prpc::VideoMetadata*>(value);
  if (value != nullptr) {
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }
  // @@protoc_insertion_point(field_unsafe_arena_set_allocated:prpc.Video.meta)
}
inline ::prpc::VideoMetadata* Video::release_meta() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::prpc::VideoMetadata* released = _impl_.meta_;
  _impl_.meta_ = nullptr;
#ifdef PROTOBUF_FORCE_COPY_IN_RELEASE
  auto* old = reinterpret_cast<::google::protobuf::MessageLite*>(released);
  released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  if (GetArenaForAllocation() == nullptr) {
    delete old;
  }
#else   // PROTOBUF_FORCE_COPY_IN_RELEASE
  if (GetArenaForAllocation() != nullptr) {
    released = ::google::protobuf::internal::DuplicateIfNonNull(released);
  }
#endif  // !PROTOBUF_FORCE_COPY_IN_RELEASE
  return released;
}
inline ::prpc::VideoMetadata* Video::unsafe_arena_release_meta() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  // @@protoc_insertion_point(field_release:prpc.Video.meta)

  _impl_._has_bits_[0] &= ~0x00000001u;
  ::prpc::VideoMetadata* temp = _impl_.meta_;
  _impl_.meta_ = nullptr;
  return temp;
}
inline ::prpc::VideoMetadata* Video::_internal_mutable_meta() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _impl_._has_bits_[0] |= 0x00000001u;
  if (_impl_.meta_ == nullptr) {
    auto* p = CreateMaybeMessage<::prpc::VideoMetadata>(GetArenaForAllocation());
    _impl_.meta_ = reinterpret_cast<::prpc::VideoMetadata*>(p);
  }
  return _impl_.meta_;
}
inline ::prpc::VideoMetadata* Video::mutable_meta() {
  ::prpc::VideoMetadata* _msg = _internal_mutable_meta();
  // @@protoc_insertion_point(field_mutable:prpc.Video.meta)
  return _msg;
}
inline void Video::set_allocated_meta(::prpc::VideoMetadata* value) {
  ::google::protobuf::Arena* message_arena = GetArenaForAllocation();
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  if (message_arena == nullptr) {
    delete reinterpret_cast<::prpc::VideoMetadata*>(_impl_.meta_);
  }

  if (value != nullptr) {
    ::google::protobuf::Arena* submessage_arena =
        ::google::protobuf::Arena::InternalGetOwningArena(reinterpret_cast<::prpc::VideoMetadata*>(value));
    if (message_arena != submessage_arena) {
      value = ::google::protobuf::internal::GetOwnedMessage(message_arena, value, submessage_arena);
    }
    _impl_._has_bits_[0] |= 0x00000001u;
  } else {
    _impl_._has_bits_[0] &= ~0x00000001u;
  }

  _impl_.meta_ = reinterpret_cast<::prpc::VideoMetadata*>(value);
  // @@protoc_insertion_point(field_set_allocated:prpc.Video.meta)
}

// repeated string subtitle_paths = 4;
inline int Video::_internal_subtitle_paths_size() const {
  return _internal_subtitle_paths().size();
}
inline int Video::subtitle_paths_size() const {
  return _internal_subtitle_paths_size();
}
inline void Video::clear_subtitle_paths() {
  _internal_mutable_subtitle_paths()->Clear();
}
inline std::string* Video::add_subtitle_paths() {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  std::string* _s = _internal_mutable_subtitle_paths()->Add();
  // @@protoc_insertion_point(field_add_mutable:prpc.Video.subtitle_paths)
  return _s;
}
inline const std::string& Video::subtitle_paths(int index) const {
  // @@protoc_insertion_point(field_get:prpc.Video.subtitle_paths)
  return _internal_subtitle_paths().Get(index);
}
inline std::string* Video::mutable_subtitle_paths(int index) {
  // @@protoc_insertion_point(field_mutable:prpc.Video.subtitle_paths)
  return _internal_mutable_subtitle_paths()->Mutable(index);
}
inline void Video::set_subtitle_paths(int index, const std::string& value) {
  _internal_mutable_subtitle_paths()->Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set:prpc.Video.subtitle_paths)
}
inline void Video::set_subtitle_paths(int index, std::string&& value) {
  _internal_mutable_subtitle_paths()->Mutable(index)->assign(std::move(value));
  // @@protoc_insertion_point(field_set:prpc.Video.subtitle_paths)
}
inline void Video::set_subtitle_paths(int index, const char* value) {
  ABSL_DCHECK(value != nullptr);
  _internal_mutable_subtitle_paths()->Mutable(index)->assign(value);
  // @@protoc_insertion_point(field_set_char:prpc.Video.subtitle_paths)
}
inline void Video::set_subtitle_paths(int index, const char* value,
                              std::size_t size) {
  _internal_mutable_subtitle_paths()->Mutable(index)->assign(
      reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_set_pointer:prpc.Video.subtitle_paths)
}
inline void Video::set_subtitle_paths(int index, absl::string_view value) {
  _internal_mutable_subtitle_paths()->Mutable(index)->assign(value.data(),
                                                     value.size());
  // @@protoc_insertion_point(field_set_string_piece:prpc.Video.subtitle_paths)
}
inline void Video::add_subtitle_paths(const std::string& value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _internal_mutable_subtitle_paths()->Add()->assign(value);
  // @@protoc_insertion_point(field_add:prpc.Video.subtitle_paths)
}
inline void Video::add_subtitle_paths(std::string&& value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _internal_mutable_subtitle_paths()->Add(std::move(value));
  // @@protoc_insertion_point(field_add:prpc.Video.subtitle_paths)
}
inline void Video::add_subtitle_paths(const char* value) {
  ABSL_DCHECK(value != nullptr);
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _internal_mutable_subtitle_paths()->Add()->assign(value);
  // @@protoc_insertion_point(field_add_char:prpc.Video.subtitle_paths)
}
inline void Video::add_subtitle_paths(const char* value, std::size_t size) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _internal_mutable_subtitle_paths()->Add()->assign(
      reinterpret_cast<const char*>(value), size);
  // @@protoc_insertion_point(field_add_pointer:prpc.Video.subtitle_paths)
}
inline void Video::add_subtitle_paths(absl::string_view value) {
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  _internal_mutable_subtitle_paths()->Add()->assign(value.data(), value.size());
  // @@protoc_insertion_point(field_add_string_piece:prpc.Video.subtitle_paths)
}
inline const ::google::protobuf::RepeatedPtrField<std::string>&
Video::subtitle_paths() const {
  // @@protoc_insertion_point(field_list:prpc.Video.subtitle_paths)
  return _internal_subtitle_paths();
}
inline ::google::protobuf::RepeatedPtrField<std::string>* Video::mutable_subtitle_paths() {
  // @@protoc_insertion_point(field_mutable_list:prpc.Video.subtitle_paths)
  PROTOBUF_TSAN_WRITE(&_impl_._tsan_detect_race);
  return _internal_mutable_subtitle_paths();
}
inline const ::google::protobuf::RepeatedPtrField<std::string>&
Video::_internal_subtitle_paths() const {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return _impl_.subtitle_paths_;
}
inline ::google::protobuf::RepeatedPtrField<std::string>*
Video::_internal_mutable_subtitle_paths() {
  PROTOBUF_TSAN_READ(&_impl_._tsan_detect_race);
  return &_impl_.subtitle_paths_;
}

#ifdef __GNUC__
#pragma GCC diagnostic pop
#endif  // __GNUC__

// @@protoc_insertion_point(namespace_scope)
}  // namespace prpc


// @@protoc_insertion_point(global_scope)

#include "google/protobuf/port_undef.inc"

#endif  // GOOGLE_PROTOBUF_INCLUDED_video_2eproto_2epb_2eh
