// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.3.0
// - protoc             v4.24.3
// source: user.proto

package prpc

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.32.0 or later.
const _ = grpc.SupportPackageIsVersion7

const (
	UserService_Register_FullMethodName          = "/prpc.UserService/Register"
	UserService_IsUsedEmail_FullMethodName       = "/prpc.UserService/IsUsedEmail"
	UserService_Login_FullMethodName             = "/prpc.UserService/Login"
	UserService_FastLogin_FullMethodName         = "/prpc.UserService/FastLogin"
	UserService_IsLogined_FullMethodName         = "/prpc.UserService/IsLogined"
	UserService_ChangePassword_FullMethodName    = "/prpc.UserService/ChangePassword"
	UserService_Download_FullMethodName          = "/prpc.UserService/Download"
	UserService_RemoveTorrent_FullMethodName     = "/prpc.UserService/RemoveTorrent"
	UserService_GetMagnetUri_FullMethodName      = "/prpc.UserService/GetMagnetUri"
	UserService_GetTorrents_FullMethodName       = "/prpc.UserService/GetTorrents"
	UserService_GetPeerInfo_FullMethodName       = "/prpc.UserService/GetPeerInfo"
	UserService_OnBtStatus_FullMethodName        = "/prpc.UserService/OnBtStatus"
	UserService_QueryBtVideos_FullMethodName     = "/prpc.UserService/QueryBtVideos"
	UserService_NewCategoryItem_FullMethodName   = "/prpc.UserService/NewCategoryItem"
	UserService_DelCategoryItem_FullMethodName   = "/prpc.UserService/DelCategoryItem"
	UserService_RenameItem_FullMethodName        = "/prpc.UserService/RenameItem"
	UserService_AddBtVideos_FullMethodName       = "/prpc.UserService/AddBtVideos"
	UserService_ShareItem_FullMethodName         = "/prpc.UserService/ShareItem"
	UserService_QuerySharedItems_FullMethodName  = "/prpc.UserService/QuerySharedItems"
	UserService_DelSharedItem_FullMethodName     = "/prpc.UserService/DelSharedItem"
	UserService_QuerySubItems_FullMethodName     = "/prpc.UserService/QuerySubItems"
	UserService_QueryItemInfo_FullMethodName     = "/prpc.UserService/QueryItemInfo"
	UserService_UploadSubtitle_FullMethodName    = "/prpc.UserService/UploadSubtitle"
	UserService_RenameBtVideoName_FullMethodName = "/prpc.UserService/RenameBtVideoName"
	UserService_GetBtMeta_FullMethodName         = "/prpc.UserService/GetBtMeta"
	UserService_NewBtHlsTask_FullMethodName      = "/prpc.UserService/NewBtHlsTask"
	UserService_JoinChatRoom_FullMethodName      = "/prpc.UserService/JoinChatRoom"
	UserService_SendMsg2ChatRoom_FullMethodName  = "/prpc.UserService/SendMsg2ChatRoom"
	UserService_AddMagnetCategory_FullMethodName = "/prpc.UserService/AddMagnetCategory"
	UserService_AddMagnetUri_FullMethodName      = "/prpc.UserService/AddMagnetUri"
	UserService_QueryMagnet_FullMethodName       = "/prpc.UserService/QueryMagnet"
	UserService_DelMagnetCategory_FullMethodName = "/prpc.UserService/DelMagnetCategory"
)

// UserServiceClient is the client API for UserService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type UserServiceClient interface {
	Register(ctx context.Context, in *RegisterInfo, opts ...grpc.CallOption) (*RegisterRet, error)
	IsUsedEmail(ctx context.Context, in *EmailInfo, opts ...grpc.CallOption) (*IsUsedEmailRet, error)
	Login(ctx context.Context, in *LoginInfo, opts ...grpc.CallOption) (*LoginRet, error)
	FastLogin(ctx context.Context, in *LoginInfo, opts ...grpc.CallOption) (*LoginRet, error)
	IsLogined(ctx context.Context, in *LoginInfo, opts ...grpc.CallOption) (*LoginRet, error)
	ChangePassword(ctx context.Context, in *ChangePasswordReq, opts ...grpc.CallOption) (*ChangePasswordRsp, error)
	Download(ctx context.Context, in *DownloadRequest, opts ...grpc.CallOption) (*DownloadRespone, error)
	RemoveTorrent(ctx context.Context, in *RemoveTorrentReq, opts ...grpc.CallOption) (*RemoveTorrentRes, error)
	GetMagnetUri(ctx context.Context, in *GetMagnetUriReq, opts ...grpc.CallOption) (*GetMagnetUriRsp, error)
	GetTorrents(ctx context.Context, in *GetTorrentsReq, opts ...grpc.CallOption) (*GetTorrentsRsp, error)
	GetPeerInfo(ctx context.Context, in *GetPeerInfoReq, opts ...grpc.CallOption) (*GetPeerInfoRsp, error)
	OnBtStatus(ctx context.Context, in *BtStatusRequest, opts ...grpc.CallOption) (UserService_OnBtStatusClient, error)
	QueryBtVideos(ctx context.Context, in *QueryBtVideosReq, opts ...grpc.CallOption) (*QueryBtVideosRes, error)
	NewCategoryItem(ctx context.Context, in *NewCategoryItemReq, opts ...grpc.CallOption) (*NewCategoryItemRes, error)
	DelCategoryItem(ctx context.Context, in *DelCategoryItemReq, opts ...grpc.CallOption) (*DelCategoryItemRes, error)
	RenameItem(ctx context.Context, in *RenameItemReq, opts ...grpc.CallOption) (*RenameItemRes, error)
	AddBtVideos(ctx context.Context, in *AddBtVideosReq, opts ...grpc.CallOption) (*AddBtVideosRes, error)
	ShareItem(ctx context.Context, in *ShareItemReq, opts ...grpc.CallOption) (*ShareItemRes, error)
	QuerySharedItems(ctx context.Context, in *QuerySharedItemsReq, opts ...grpc.CallOption) (*QuerySharedItemsRes, error)
	DelSharedItem(ctx context.Context, in *DelSharedItemReq, opts ...grpc.CallOption) (*DelSharedItemRes, error)
	QuerySubItems(ctx context.Context, in *QuerySubItemsReq, opts ...grpc.CallOption) (*QuerySubItemsRes, error)
	QueryItemInfo(ctx context.Context, in *QueryItemInfoReq, opts ...grpc.CallOption) (*QueryItemInfoRes, error)
	UploadSubtitle(ctx context.Context, in *UploadSubtitleReq, opts ...grpc.CallOption) (*UploadSubtitleRes, error)
	RenameBtVideoName(ctx context.Context, in *RenameBtVideoNameReq, opts ...grpc.CallOption) (*RenameBtVideoNameRsp, error)
	GetBtMeta(ctx context.Context, in *GetBtMetaReq, opts ...grpc.CallOption) (*GetBtMetaRsp, error)
	NewBtHlsTask(ctx context.Context, in *NewBtHlsTaskReq, opts ...grpc.CallOption) (*NewBtHlsTaskRsp, error)
	JoinChatRoom(ctx context.Context, in *JoinChatRoomReq, opts ...grpc.CallOption) (UserService_JoinChatRoomClient, error)
	SendMsg2ChatRoom(ctx context.Context, in *SendMsg2ChatRoomReq, opts ...grpc.CallOption) (*SendMsg2ChatRoomRes, error)
	AddMagnetCategory(ctx context.Context, in *AddMagnetCategoryReq, opts ...grpc.CallOption) (*AddMagnetCategoryRsp, error)
	AddMagnetUri(ctx context.Context, in *AddMagnetUriReq, opts ...grpc.CallOption) (*AddMagnetUriRsp, error)
	QueryMagnet(ctx context.Context, in *QueryMagnetReq, opts ...grpc.CallOption) (*QueryMagnetRsp, error)
	DelMagnetCategory(ctx context.Context, in *DelMagnetCategoryReq, opts ...grpc.CallOption) (*DelMagnetCategoryRsp, error)
}

type userServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewUserServiceClient(cc grpc.ClientConnInterface) UserServiceClient {
	return &userServiceClient{cc}
}

func (c *userServiceClient) Register(ctx context.Context, in *RegisterInfo, opts ...grpc.CallOption) (*RegisterRet, error) {
	out := new(RegisterRet)
	err := c.cc.Invoke(ctx, UserService_Register_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) IsUsedEmail(ctx context.Context, in *EmailInfo, opts ...grpc.CallOption) (*IsUsedEmailRet, error) {
	out := new(IsUsedEmailRet)
	err := c.cc.Invoke(ctx, UserService_IsUsedEmail_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) Login(ctx context.Context, in *LoginInfo, opts ...grpc.CallOption) (*LoginRet, error) {
	out := new(LoginRet)
	err := c.cc.Invoke(ctx, UserService_Login_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) FastLogin(ctx context.Context, in *LoginInfo, opts ...grpc.CallOption) (*LoginRet, error) {
	out := new(LoginRet)
	err := c.cc.Invoke(ctx, UserService_FastLogin_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) IsLogined(ctx context.Context, in *LoginInfo, opts ...grpc.CallOption) (*LoginRet, error) {
	out := new(LoginRet)
	err := c.cc.Invoke(ctx, UserService_IsLogined_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) ChangePassword(ctx context.Context, in *ChangePasswordReq, opts ...grpc.CallOption) (*ChangePasswordRsp, error) {
	out := new(ChangePasswordRsp)
	err := c.cc.Invoke(ctx, UserService_ChangePassword_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) Download(ctx context.Context, in *DownloadRequest, opts ...grpc.CallOption) (*DownloadRespone, error) {
	out := new(DownloadRespone)
	err := c.cc.Invoke(ctx, UserService_Download_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) RemoveTorrent(ctx context.Context, in *RemoveTorrentReq, opts ...grpc.CallOption) (*RemoveTorrentRes, error) {
	out := new(RemoveTorrentRes)
	err := c.cc.Invoke(ctx, UserService_RemoveTorrent_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetMagnetUri(ctx context.Context, in *GetMagnetUriReq, opts ...grpc.CallOption) (*GetMagnetUriRsp, error) {
	out := new(GetMagnetUriRsp)
	err := c.cc.Invoke(ctx, UserService_GetMagnetUri_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetTorrents(ctx context.Context, in *GetTorrentsReq, opts ...grpc.CallOption) (*GetTorrentsRsp, error) {
	out := new(GetTorrentsRsp)
	err := c.cc.Invoke(ctx, UserService_GetTorrents_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetPeerInfo(ctx context.Context, in *GetPeerInfoReq, opts ...grpc.CallOption) (*GetPeerInfoRsp, error) {
	out := new(GetPeerInfoRsp)
	err := c.cc.Invoke(ctx, UserService_GetPeerInfo_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) OnBtStatus(ctx context.Context, in *BtStatusRequest, opts ...grpc.CallOption) (UserService_OnBtStatusClient, error) {
	stream, err := c.cc.NewStream(ctx, &UserService_ServiceDesc.Streams[0], UserService_OnBtStatus_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &userServiceOnBtStatusClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type UserService_OnBtStatusClient interface {
	Recv() (*BtStatusRespone, error)
	grpc.ClientStream
}

type userServiceOnBtStatusClient struct {
	grpc.ClientStream
}

func (x *userServiceOnBtStatusClient) Recv() (*BtStatusRespone, error) {
	m := new(BtStatusRespone)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *userServiceClient) QueryBtVideos(ctx context.Context, in *QueryBtVideosReq, opts ...grpc.CallOption) (*QueryBtVideosRes, error) {
	out := new(QueryBtVideosRes)
	err := c.cc.Invoke(ctx, UserService_QueryBtVideos_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) NewCategoryItem(ctx context.Context, in *NewCategoryItemReq, opts ...grpc.CallOption) (*NewCategoryItemRes, error) {
	out := new(NewCategoryItemRes)
	err := c.cc.Invoke(ctx, UserService_NewCategoryItem_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) DelCategoryItem(ctx context.Context, in *DelCategoryItemReq, opts ...grpc.CallOption) (*DelCategoryItemRes, error) {
	out := new(DelCategoryItemRes)
	err := c.cc.Invoke(ctx, UserService_DelCategoryItem_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) RenameItem(ctx context.Context, in *RenameItemReq, opts ...grpc.CallOption) (*RenameItemRes, error) {
	out := new(RenameItemRes)
	err := c.cc.Invoke(ctx, UserService_RenameItem_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) AddBtVideos(ctx context.Context, in *AddBtVideosReq, opts ...grpc.CallOption) (*AddBtVideosRes, error) {
	out := new(AddBtVideosRes)
	err := c.cc.Invoke(ctx, UserService_AddBtVideos_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) ShareItem(ctx context.Context, in *ShareItemReq, opts ...grpc.CallOption) (*ShareItemRes, error) {
	out := new(ShareItemRes)
	err := c.cc.Invoke(ctx, UserService_ShareItem_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) QuerySharedItems(ctx context.Context, in *QuerySharedItemsReq, opts ...grpc.CallOption) (*QuerySharedItemsRes, error) {
	out := new(QuerySharedItemsRes)
	err := c.cc.Invoke(ctx, UserService_QuerySharedItems_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) DelSharedItem(ctx context.Context, in *DelSharedItemReq, opts ...grpc.CallOption) (*DelSharedItemRes, error) {
	out := new(DelSharedItemRes)
	err := c.cc.Invoke(ctx, UserService_DelSharedItem_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) QuerySubItems(ctx context.Context, in *QuerySubItemsReq, opts ...grpc.CallOption) (*QuerySubItemsRes, error) {
	out := new(QuerySubItemsRes)
	err := c.cc.Invoke(ctx, UserService_QuerySubItems_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) QueryItemInfo(ctx context.Context, in *QueryItemInfoReq, opts ...grpc.CallOption) (*QueryItemInfoRes, error) {
	out := new(QueryItemInfoRes)
	err := c.cc.Invoke(ctx, UserService_QueryItemInfo_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) UploadSubtitle(ctx context.Context, in *UploadSubtitleReq, opts ...grpc.CallOption) (*UploadSubtitleRes, error) {
	out := new(UploadSubtitleRes)
	err := c.cc.Invoke(ctx, UserService_UploadSubtitle_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) RenameBtVideoName(ctx context.Context, in *RenameBtVideoNameReq, opts ...grpc.CallOption) (*RenameBtVideoNameRsp, error) {
	out := new(RenameBtVideoNameRsp)
	err := c.cc.Invoke(ctx, UserService_RenameBtVideoName_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) GetBtMeta(ctx context.Context, in *GetBtMetaReq, opts ...grpc.CallOption) (*GetBtMetaRsp, error) {
	out := new(GetBtMetaRsp)
	err := c.cc.Invoke(ctx, UserService_GetBtMeta_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) NewBtHlsTask(ctx context.Context, in *NewBtHlsTaskReq, opts ...grpc.CallOption) (*NewBtHlsTaskRsp, error) {
	out := new(NewBtHlsTaskRsp)
	err := c.cc.Invoke(ctx, UserService_NewBtHlsTask_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) JoinChatRoom(ctx context.Context, in *JoinChatRoomReq, opts ...grpc.CallOption) (UserService_JoinChatRoomClient, error) {
	stream, err := c.cc.NewStream(ctx, &UserService_ServiceDesc.Streams[1], UserService_JoinChatRoom_FullMethodName, opts...)
	if err != nil {
		return nil, err
	}
	x := &userServiceJoinChatRoomClient{stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

type UserService_JoinChatRoomClient interface {
	Recv() (*JoinChatRoomRes, error)
	grpc.ClientStream
}

type userServiceJoinChatRoomClient struct {
	grpc.ClientStream
}

func (x *userServiceJoinChatRoomClient) Recv() (*JoinChatRoomRes, error) {
	m := new(JoinChatRoomRes)
	if err := x.ClientStream.RecvMsg(m); err != nil {
		return nil, err
	}
	return m, nil
}

func (c *userServiceClient) SendMsg2ChatRoom(ctx context.Context, in *SendMsg2ChatRoomReq, opts ...grpc.CallOption) (*SendMsg2ChatRoomRes, error) {
	out := new(SendMsg2ChatRoomRes)
	err := c.cc.Invoke(ctx, UserService_SendMsg2ChatRoom_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) AddMagnetCategory(ctx context.Context, in *AddMagnetCategoryReq, opts ...grpc.CallOption) (*AddMagnetCategoryRsp, error) {
	out := new(AddMagnetCategoryRsp)
	err := c.cc.Invoke(ctx, UserService_AddMagnetCategory_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) AddMagnetUri(ctx context.Context, in *AddMagnetUriReq, opts ...grpc.CallOption) (*AddMagnetUriRsp, error) {
	out := new(AddMagnetUriRsp)
	err := c.cc.Invoke(ctx, UserService_AddMagnetUri_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) QueryMagnet(ctx context.Context, in *QueryMagnetReq, opts ...grpc.CallOption) (*QueryMagnetRsp, error) {
	out := new(QueryMagnetRsp)
	err := c.cc.Invoke(ctx, UserService_QueryMagnet_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userServiceClient) DelMagnetCategory(ctx context.Context, in *DelMagnetCategoryReq, opts ...grpc.CallOption) (*DelMagnetCategoryRsp, error) {
	out := new(DelMagnetCategoryRsp)
	err := c.cc.Invoke(ctx, UserService_DelMagnetCategory_FullMethodName, in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServiceServer is the server API for UserService service.
// All implementations must embed UnimplementedUserServiceServer
// for forward compatibility
type UserServiceServer interface {
	Register(context.Context, *RegisterInfo) (*RegisterRet, error)
	IsUsedEmail(context.Context, *EmailInfo) (*IsUsedEmailRet, error)
	Login(context.Context, *LoginInfo) (*LoginRet, error)
	FastLogin(context.Context, *LoginInfo) (*LoginRet, error)
	IsLogined(context.Context, *LoginInfo) (*LoginRet, error)
	ChangePassword(context.Context, *ChangePasswordReq) (*ChangePasswordRsp, error)
	Download(context.Context, *DownloadRequest) (*DownloadRespone, error)
	RemoveTorrent(context.Context, *RemoveTorrentReq) (*RemoveTorrentRes, error)
	GetMagnetUri(context.Context, *GetMagnetUriReq) (*GetMagnetUriRsp, error)
	GetTorrents(context.Context, *GetTorrentsReq) (*GetTorrentsRsp, error)
	GetPeerInfo(context.Context, *GetPeerInfoReq) (*GetPeerInfoRsp, error)
	OnBtStatus(*BtStatusRequest, UserService_OnBtStatusServer) error
	QueryBtVideos(context.Context, *QueryBtVideosReq) (*QueryBtVideosRes, error)
	NewCategoryItem(context.Context, *NewCategoryItemReq) (*NewCategoryItemRes, error)
	DelCategoryItem(context.Context, *DelCategoryItemReq) (*DelCategoryItemRes, error)
	RenameItem(context.Context, *RenameItemReq) (*RenameItemRes, error)
	AddBtVideos(context.Context, *AddBtVideosReq) (*AddBtVideosRes, error)
	ShareItem(context.Context, *ShareItemReq) (*ShareItemRes, error)
	QuerySharedItems(context.Context, *QuerySharedItemsReq) (*QuerySharedItemsRes, error)
	DelSharedItem(context.Context, *DelSharedItemReq) (*DelSharedItemRes, error)
	QuerySubItems(context.Context, *QuerySubItemsReq) (*QuerySubItemsRes, error)
	QueryItemInfo(context.Context, *QueryItemInfoReq) (*QueryItemInfoRes, error)
	UploadSubtitle(context.Context, *UploadSubtitleReq) (*UploadSubtitleRes, error)
	RenameBtVideoName(context.Context, *RenameBtVideoNameReq) (*RenameBtVideoNameRsp, error)
	GetBtMeta(context.Context, *GetBtMetaReq) (*GetBtMetaRsp, error)
	NewBtHlsTask(context.Context, *NewBtHlsTaskReq) (*NewBtHlsTaskRsp, error)
	JoinChatRoom(*JoinChatRoomReq, UserService_JoinChatRoomServer) error
	SendMsg2ChatRoom(context.Context, *SendMsg2ChatRoomReq) (*SendMsg2ChatRoomRes, error)
	AddMagnetCategory(context.Context, *AddMagnetCategoryReq) (*AddMagnetCategoryRsp, error)
	AddMagnetUri(context.Context, *AddMagnetUriReq) (*AddMagnetUriRsp, error)
	QueryMagnet(context.Context, *QueryMagnetReq) (*QueryMagnetRsp, error)
	DelMagnetCategory(context.Context, *DelMagnetCategoryReq) (*DelMagnetCategoryRsp, error)
	mustEmbedUnimplementedUserServiceServer()
}

// UnimplementedUserServiceServer must be embedded to have forward compatible implementations.
type UnimplementedUserServiceServer struct {
}

func (UnimplementedUserServiceServer) Register(context.Context, *RegisterInfo) (*RegisterRet, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Register not implemented")
}
func (UnimplementedUserServiceServer) IsUsedEmail(context.Context, *EmailInfo) (*IsUsedEmailRet, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsUsedEmail not implemented")
}
func (UnimplementedUserServiceServer) Login(context.Context, *LoginInfo) (*LoginRet, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Login not implemented")
}
func (UnimplementedUserServiceServer) FastLogin(context.Context, *LoginInfo) (*LoginRet, error) {
	return nil, status.Errorf(codes.Unimplemented, "method FastLogin not implemented")
}
func (UnimplementedUserServiceServer) IsLogined(context.Context, *LoginInfo) (*LoginRet, error) {
	return nil, status.Errorf(codes.Unimplemented, "method IsLogined not implemented")
}
func (UnimplementedUserServiceServer) ChangePassword(context.Context, *ChangePasswordReq) (*ChangePasswordRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ChangePassword not implemented")
}
func (UnimplementedUserServiceServer) Download(context.Context, *DownloadRequest) (*DownloadRespone, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Download not implemented")
}
func (UnimplementedUserServiceServer) RemoveTorrent(context.Context, *RemoveTorrentReq) (*RemoveTorrentRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RemoveTorrent not implemented")
}
func (UnimplementedUserServiceServer) GetMagnetUri(context.Context, *GetMagnetUriReq) (*GetMagnetUriRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetMagnetUri not implemented")
}
func (UnimplementedUserServiceServer) GetTorrents(context.Context, *GetTorrentsReq) (*GetTorrentsRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetTorrents not implemented")
}
func (UnimplementedUserServiceServer) GetPeerInfo(context.Context, *GetPeerInfoReq) (*GetPeerInfoRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetPeerInfo not implemented")
}
func (UnimplementedUserServiceServer) OnBtStatus(*BtStatusRequest, UserService_OnBtStatusServer) error {
	return status.Errorf(codes.Unimplemented, "method OnBtStatus not implemented")
}
func (UnimplementedUserServiceServer) QueryBtVideos(context.Context, *QueryBtVideosReq) (*QueryBtVideosRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryBtVideos not implemented")
}
func (UnimplementedUserServiceServer) NewCategoryItem(context.Context, *NewCategoryItemReq) (*NewCategoryItemRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewCategoryItem not implemented")
}
func (UnimplementedUserServiceServer) DelCategoryItem(context.Context, *DelCategoryItemReq) (*DelCategoryItemRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DelCategoryItem not implemented")
}
func (UnimplementedUserServiceServer) RenameItem(context.Context, *RenameItemReq) (*RenameItemRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RenameItem not implemented")
}
func (UnimplementedUserServiceServer) AddBtVideos(context.Context, *AddBtVideosReq) (*AddBtVideosRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddBtVideos not implemented")
}
func (UnimplementedUserServiceServer) ShareItem(context.Context, *ShareItemReq) (*ShareItemRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method ShareItem not implemented")
}
func (UnimplementedUserServiceServer) QuerySharedItems(context.Context, *QuerySharedItemsReq) (*QuerySharedItemsRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QuerySharedItems not implemented")
}
func (UnimplementedUserServiceServer) DelSharedItem(context.Context, *DelSharedItemReq) (*DelSharedItemRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DelSharedItem not implemented")
}
func (UnimplementedUserServiceServer) QuerySubItems(context.Context, *QuerySubItemsReq) (*QuerySubItemsRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QuerySubItems not implemented")
}
func (UnimplementedUserServiceServer) QueryItemInfo(context.Context, *QueryItemInfoReq) (*QueryItemInfoRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryItemInfo not implemented")
}
func (UnimplementedUserServiceServer) UploadSubtitle(context.Context, *UploadSubtitleReq) (*UploadSubtitleRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method UploadSubtitle not implemented")
}
func (UnimplementedUserServiceServer) RenameBtVideoName(context.Context, *RenameBtVideoNameReq) (*RenameBtVideoNameRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method RenameBtVideoName not implemented")
}
func (UnimplementedUserServiceServer) GetBtMeta(context.Context, *GetBtMetaReq) (*GetBtMetaRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetBtMeta not implemented")
}
func (UnimplementedUserServiceServer) NewBtHlsTask(context.Context, *NewBtHlsTaskReq) (*NewBtHlsTaskRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method NewBtHlsTask not implemented")
}
func (UnimplementedUserServiceServer) JoinChatRoom(*JoinChatRoomReq, UserService_JoinChatRoomServer) error {
	return status.Errorf(codes.Unimplemented, "method JoinChatRoom not implemented")
}
func (UnimplementedUserServiceServer) SendMsg2ChatRoom(context.Context, *SendMsg2ChatRoomReq) (*SendMsg2ChatRoomRes, error) {
	return nil, status.Errorf(codes.Unimplemented, "method SendMsg2ChatRoom not implemented")
}
func (UnimplementedUserServiceServer) AddMagnetCategory(context.Context, *AddMagnetCategoryReq) (*AddMagnetCategoryRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddMagnetCategory not implemented")
}
func (UnimplementedUserServiceServer) AddMagnetUri(context.Context, *AddMagnetUriReq) (*AddMagnetUriRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method AddMagnetUri not implemented")
}
func (UnimplementedUserServiceServer) QueryMagnet(context.Context, *QueryMagnetReq) (*QueryMagnetRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method QueryMagnet not implemented")
}
func (UnimplementedUserServiceServer) DelMagnetCategory(context.Context, *DelMagnetCategoryReq) (*DelMagnetCategoryRsp, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DelMagnetCategory not implemented")
}
func (UnimplementedUserServiceServer) mustEmbedUnimplementedUserServiceServer() {}

// UnsafeUserServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to UserServiceServer will
// result in compilation errors.
type UnsafeUserServiceServer interface {
	mustEmbedUnimplementedUserServiceServer()
}

func RegisterUserServiceServer(s grpc.ServiceRegistrar, srv UserServiceServer) {
	s.RegisterService(&UserService_ServiceDesc, srv)
}

func _UserService_Register_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RegisterInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Register(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_Register_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Register(ctx, req.(*RegisterInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_IsUsedEmail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EmailInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).IsUsedEmail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_IsUsedEmail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).IsUsedEmail(ctx, req.(*EmailInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_Login_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Login(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_Login_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Login(ctx, req.(*LoginInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_FastLogin_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).FastLogin(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_FastLogin_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).FastLogin(ctx, req.(*LoginInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_IsLogined_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(LoginInfo)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).IsLogined(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_IsLogined_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).IsLogined(ctx, req.(*LoginInfo))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_ChangePassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangePasswordReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).ChangePassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_ChangePassword_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).ChangePassword(ctx, req.(*ChangePasswordReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_Download_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DownloadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).Download(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_Download_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).Download(ctx, req.(*DownloadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_RemoveTorrent_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RemoveTorrentReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).RemoveTorrent(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_RemoveTorrent_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).RemoveTorrent(ctx, req.(*RemoveTorrentReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetMagnetUri_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetMagnetUriReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetMagnetUri(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_GetMagnetUri_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetMagnetUri(ctx, req.(*GetMagnetUriReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetTorrents_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetTorrentsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetTorrents(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_GetTorrents_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetTorrents(ctx, req.(*GetTorrentsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetPeerInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetPeerInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetPeerInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_GetPeerInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetPeerInfo(ctx, req.(*GetPeerInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_OnBtStatus_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(BtStatusRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(UserServiceServer).OnBtStatus(m, &userServiceOnBtStatusServer{stream})
}

type UserService_OnBtStatusServer interface {
	Send(*BtStatusRespone) error
	grpc.ServerStream
}

type userServiceOnBtStatusServer struct {
	grpc.ServerStream
}

func (x *userServiceOnBtStatusServer) Send(m *BtStatusRespone) error {
	return x.ServerStream.SendMsg(m)
}

func _UserService_QueryBtVideos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryBtVideosReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).QueryBtVideos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_QueryBtVideos_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).QueryBtVideos(ctx, req.(*QueryBtVideosReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_NewCategoryItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewCategoryItemReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).NewCategoryItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_NewCategoryItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).NewCategoryItem(ctx, req.(*NewCategoryItemReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_DelCategoryItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelCategoryItemReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).DelCategoryItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_DelCategoryItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).DelCategoryItem(ctx, req.(*DelCategoryItemReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_RenameItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenameItemReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).RenameItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_RenameItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).RenameItem(ctx, req.(*RenameItemReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_AddBtVideos_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddBtVideosReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).AddBtVideos(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_AddBtVideos_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).AddBtVideos(ctx, req.(*AddBtVideosReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_ShareItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ShareItemReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).ShareItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_ShareItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).ShareItem(ctx, req.(*ShareItemReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_QuerySharedItems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuerySharedItemsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).QuerySharedItems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_QuerySharedItems_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).QuerySharedItems(ctx, req.(*QuerySharedItemsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_DelSharedItem_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelSharedItemReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).DelSharedItem(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_DelSharedItem_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).DelSharedItem(ctx, req.(*DelSharedItemReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_QuerySubItems_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QuerySubItemsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).QuerySubItems(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_QuerySubItems_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).QuerySubItems(ctx, req.(*QuerySubItemsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_QueryItemInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryItemInfoReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).QueryItemInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_QueryItemInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).QueryItemInfo(ctx, req.(*QueryItemInfoReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_UploadSubtitle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UploadSubtitleReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).UploadSubtitle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_UploadSubtitle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).UploadSubtitle(ctx, req.(*UploadSubtitleReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_RenameBtVideoName_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RenameBtVideoNameReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).RenameBtVideoName(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_RenameBtVideoName_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).RenameBtVideoName(ctx, req.(*RenameBtVideoNameReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_GetBtMeta_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBtMetaReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).GetBtMeta(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_GetBtMeta_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).GetBtMeta(ctx, req.(*GetBtMetaReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_NewBtHlsTask_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NewBtHlsTaskReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).NewBtHlsTask(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_NewBtHlsTask_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).NewBtHlsTask(ctx, req.(*NewBtHlsTaskReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_JoinChatRoom_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(JoinChatRoomReq)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(UserServiceServer).JoinChatRoom(m, &userServiceJoinChatRoomServer{stream})
}

type UserService_JoinChatRoomServer interface {
	Send(*JoinChatRoomRes) error
	grpc.ServerStream
}

type userServiceJoinChatRoomServer struct {
	grpc.ServerStream
}

func (x *userServiceJoinChatRoomServer) Send(m *JoinChatRoomRes) error {
	return x.ServerStream.SendMsg(m)
}

func _UserService_SendMsg2ChatRoom_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SendMsg2ChatRoomReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).SendMsg2ChatRoom(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_SendMsg2ChatRoom_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).SendMsg2ChatRoom(ctx, req.(*SendMsg2ChatRoomReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_AddMagnetCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddMagnetCategoryReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).AddMagnetCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_AddMagnetCategory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).AddMagnetCategory(ctx, req.(*AddMagnetCategoryReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_AddMagnetUri_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AddMagnetUriReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).AddMagnetUri(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_AddMagnetUri_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).AddMagnetUri(ctx, req.(*AddMagnetUriReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_QueryMagnet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(QueryMagnetReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).QueryMagnet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_QueryMagnet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).QueryMagnet(ctx, req.(*QueryMagnetReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _UserService_DelMagnetCategory_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DelMagnetCategoryReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServiceServer).DelMagnetCategory(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: UserService_DelMagnetCategory_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServiceServer).DelMagnetCategory(ctx, req.(*DelMagnetCategoryReq))
	}
	return interceptor(ctx, in, info, handler)
}

// UserService_ServiceDesc is the grpc.ServiceDesc for UserService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var UserService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "prpc.UserService",
	HandlerType: (*UserServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Register",
			Handler:    _UserService_Register_Handler,
		},
		{
			MethodName: "IsUsedEmail",
			Handler:    _UserService_IsUsedEmail_Handler,
		},
		{
			MethodName: "Login",
			Handler:    _UserService_Login_Handler,
		},
		{
			MethodName: "FastLogin",
			Handler:    _UserService_FastLogin_Handler,
		},
		{
			MethodName: "IsLogined",
			Handler:    _UserService_IsLogined_Handler,
		},
		{
			MethodName: "ChangePassword",
			Handler:    _UserService_ChangePassword_Handler,
		},
		{
			MethodName: "Download",
			Handler:    _UserService_Download_Handler,
		},
		{
			MethodName: "RemoveTorrent",
			Handler:    _UserService_RemoveTorrent_Handler,
		},
		{
			MethodName: "GetMagnetUri",
			Handler:    _UserService_GetMagnetUri_Handler,
		},
		{
			MethodName: "GetTorrents",
			Handler:    _UserService_GetTorrents_Handler,
		},
		{
			MethodName: "GetPeerInfo",
			Handler:    _UserService_GetPeerInfo_Handler,
		},
		{
			MethodName: "QueryBtVideos",
			Handler:    _UserService_QueryBtVideos_Handler,
		},
		{
			MethodName: "NewCategoryItem",
			Handler:    _UserService_NewCategoryItem_Handler,
		},
		{
			MethodName: "DelCategoryItem",
			Handler:    _UserService_DelCategoryItem_Handler,
		},
		{
			MethodName: "RenameItem",
			Handler:    _UserService_RenameItem_Handler,
		},
		{
			MethodName: "AddBtVideos",
			Handler:    _UserService_AddBtVideos_Handler,
		},
		{
			MethodName: "ShareItem",
			Handler:    _UserService_ShareItem_Handler,
		},
		{
			MethodName: "QuerySharedItems",
			Handler:    _UserService_QuerySharedItems_Handler,
		},
		{
			MethodName: "DelSharedItem",
			Handler:    _UserService_DelSharedItem_Handler,
		},
		{
			MethodName: "QuerySubItems",
			Handler:    _UserService_QuerySubItems_Handler,
		},
		{
			MethodName: "QueryItemInfo",
			Handler:    _UserService_QueryItemInfo_Handler,
		},
		{
			MethodName: "UploadSubtitle",
			Handler:    _UserService_UploadSubtitle_Handler,
		},
		{
			MethodName: "RenameBtVideoName",
			Handler:    _UserService_RenameBtVideoName_Handler,
		},
		{
			MethodName: "GetBtMeta",
			Handler:    _UserService_GetBtMeta_Handler,
		},
		{
			MethodName: "NewBtHlsTask",
			Handler:    _UserService_NewBtHlsTask_Handler,
		},
		{
			MethodName: "SendMsg2ChatRoom",
			Handler:    _UserService_SendMsg2ChatRoom_Handler,
		},
		{
			MethodName: "AddMagnetCategory",
			Handler:    _UserService_AddMagnetCategory_Handler,
		},
		{
			MethodName: "AddMagnetUri",
			Handler:    _UserService_AddMagnetUri_Handler,
		},
		{
			MethodName: "QueryMagnet",
			Handler:    _UserService_QueryMagnet_Handler,
		},
		{
			MethodName: "DelMagnetCategory",
			Handler:    _UserService_DelMagnetCategory_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "OnBtStatus",
			Handler:       _UserService_OnBtStatus_Handler,
			ServerStreams: true,
		},
		{
			StreamName:    "JoinChatRoom",
			Handler:       _UserService_JoinChatRoom_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "user.proto",
}
